### ISSUE TITLE
Add syntactic sugar do define services with @service, @endpoint

### ISSUE THREAD

**Issue by petrarca** [charbonnierg/nats-micro#2]
Hello Guillome, thank you for our great work here!!! 
I have, as a kind of of POC add some syntactic sugar on top of your excellent library, especial for fast prototyping.
See here:
https://github.com/petrarca/hazelnats

Would great if you can incorporate something like this (feel free to use code here) or provide such kind of a solution in the future.

Regards
Wolfgang Miller

**Comment by charbonnierg** [comment]
Thanks for the suggestion and the examples !

I have other items higher in my backlog such as:

- Addind tests to this repo: https://github.com/charbonats/nats-request-many
- Remove the `request_many` implementation from the nats-micro package and depend on the nats-request-many package
- Adding tests for the existing code in nats-micro

I don't feel adding more features until there are some basic tests.

I'll get back to this issue and ping you once the above points are done. Some remarks I can already give you:

- Using `pydantic` instead of `fastapi` seems much more appropriate to handle serialization/deserialization.
- I didn't see a way to properly return an error in the examples you gave me
- It seems a bit too magical for me to start all services decorated, because you might start different services based on which files you import. This is not acceptable IMO, as it leads to behaviours difficult to debug and maintain. I'd rather see an explicit list of services to start somewhere in the code.

**Comment by petrarca** [comment]
Fully agree on your feedback. Should not have to much magic behind the scenes. Especial for prototyping etc. would be great to have this kind of "FastAPI" like approach (declarative and payload/response conversion). Waiting for your ping.
```
...
@service(name = "patients")
class PatientService:
	@endpoint
	async def get_patient(self, id: str) -> dict:
		return { 'id' : id}

NatsMicroService
	.client()
	.register(PatientService())
	.run()
```

**Comment by charbonnierg** [comment]
I stopped pushing changes to this repo and moved [here](https://github.com/charbonats/nats-micro).

I added tests, and fixed some bugs by the way 😅

You can check this example: https://github.com/charbonats/nats-micro/blob/main/examples/with_decorators.py

Services are created using the `@micro.sdk.service` decorator, which is a wrapper around [dataclasses.dataclass](https://docs.python.org/3/library/dataclasses.html) so you don't have to write __init__ methods.

All methods decorated with `@micro.sdk.endpoint` on a service class are used to define an endpoint unless the argument `disabled` is `True` (so you don't have to comment a whole block of code to test your app with or without an endpoint)

Services are started using the `micro.sdk.run` function which can be used directly under `if __name__ == "__main__":`. The function accepts a list of services with the `services` argument

If you need more control to create your service (for example you need to be within an async scope to initialize your service), you can use a custom setup function using the `setup` argument. The setup function is executed after NATS client is connected.

If you need even more control and want to change how connection is done, you can use a custom connect function using the `connect` argument. The connect function is executed right after signals are trapped (if configured to, signals are not trapped by default).

There is no serialization/deserialization as you showed in your example, I want to think more about this.

I'm closing this issue, but I would be glad to here your thoughts about those changes in [new issue](https://github.com/charbonats/nats-micro/issues)
